Cargo.toml
I'm not exactly sure why this is required, but it seems to be something
about the `syn` dependency requirement and/or usage.
=> ghost: update to 0.1.1

src/lib.rs
Okay, so undefined behavior would be pretty hard to trigger, but it *is* possible (I think):
* While constructor methods are being called pre-main to register with inventory's Registry...
* Have a second thread (started by another constructor method) iterate plugins.
This would be pretty boneheaded thing to do, and won't return the full list of plugins, but I've seen worse in shipped code.
https://github.com/dtolnay/inventory/blob/31b0974e6ab749967ee3506d166302c5a138221c/src/lib.rs#L154-L165
`new.next` is set *after* `new` has been inserted into the registry.
* Every `unsafe { prev.as_ref() }` on another thread possibly returns a `&Node<T>` to the `&mut Node<T>` we're modifying, which is Undefined Behavior.
* Even if it weren't UB, this would temporarilly truncate the registry to a single …
=> Soundness:  Modify new before it's visible in the registry, not after.

src/lib.rs
=> no_std support

impl/src/lib.rs
The benefit of this should be pretty obvious: in order to allow improvements to macro santization, allow for passing the crate containing inventory as a path. This allows you to ensure there isn't a name collision in the local scope.
=> Allow specifying absolute crate path

src/lib.rs
Allows cloning the iterator over plugins
=> Implement Clone for iter

src/lib.rs, tests/ui/collect-unsized.stderr, tests/ui/non-sync.rs, tests/ui/non-sync.stderr
We hand out `&'static T` references onto arbitrary threads when iterating the inventory, so `T: Sync` is necessary.
=> Require inventory element type to be Sync

examples/flags.rs, src/lib.rs, tests/ui/collect-unsized.stderr, tests/ui/submit-unrecognized.stderr
The Rust standard library is not yet properly initialized during life before main, so sticking things like the following in there is problematic and must not be allowed.
```rust
inventory::submit!({
std::println!("???");
std::thread::spawn(...);
Thing {}
});
```
=> Require inventory element type to be const constructed

Cargo.toml, src/lib.rs
See https://github.com/dtolnay/ghost/pull/10.
=> Let ghost crate natively handle the documentation

Cargo.toml
Not sure why this was made 0.2.0. I don't see any relevant API change relative to ctor 0.1.26.
=> Update ctor dependency to 0.2

Cargo.toml, README.md, src/lib.rs
I am interested in experimenting with `#[used(linker)]` and don't want to go through the ctor crate for iterating on that.
=> Replace ctor dependency with our own link_section attributes

src/lib.rs, tests/ui/outer-attr.rs, tests/ui/outer-attr.stderr, tests/ui/submit-unrecognized.stderr, tests/ui/used-linker.rs, tests/ui/used-linker.stderr
```rust
inventory::submit! {
#![used(linker)]
Foo::new(...)
}
```
=> Add a way to use `#[used(linker)]`

.github/workflows/ci.yml, src/lib.rs, tests/test.rs
https://github.com/rust-lang/rust/issues/113941
=> Work around ICE in rustc: the naive layout isn't refined by the actual layout

src/lib.rs
```console
---- test_iter stdout ----
thread 'test_iter' panicked at tests/test.rs:7:5:
assertion `left == right` failed
left: 0
right: 8
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
failures:
test_iter
```
It seems https://github.com/rust-lang/rust/pull/115277 in nightly-2023-08-30 affected the size of this type as originally written.
=> Fix zero sizing of Iter<T>

src/lib.rs
See https://github.com/dtolnay/ghost/pull/20.
```console
error[E0392]: parameter `T` is never used
--> src/lib.rs:242:21
|
242 |     pub struct iter<T>;
|                     ^ unused parameter
|
= help: consider removing `T`, referring to it in a field, or using a marker such as `core::marker::PhantomData`
= help: if you intended `T` to be a const parameter, use `const T: usize` instead
```
=> Eliminate `cfg(doc)`

src/lib.rs
This is allow-by-default for now in 2021 edition, but will become warn-by-default in 2024 edition.
=> Turn on deny(unsafe_op_in_unsafe_fn)

src/lib.rs
The `const _` language feature did not exist yet when this code was written.
=> Move iterator internals to underscore const

src/lib.rs
Alternative take on https://github.com/dtolnay/inventory/pull/66.
Adds a feature called `force-init-array-section` to force `__do_submit!` to assign `static __CTOR` to the `.init_array` section, regardless of the platform. This enables support for arbitrary platforms that support `.init_array` constructors.
Unlike https://github.com/dtolnay/inventory/pull/66, this is an intrinsic feature of the `inventory` crate.
=> Support `target_os = "none"`

src/lib.rs
Thanks to some [recent work](https://github.com/llvm/llvm-project/pull/119533) on how LLVM handles `.init_array` for WebAssembly targets, the `emscripten` and `wasi` OSs should now work as of LLVM 19.1.6 and Rust `nightly-2024-12-19`.
More information and an example is in the comment and thread at https://github.com/dtolnay/inventory/issues/71#issuecomment-2553150709.
=> Use `.init_array` section on wasi and emscripten

Cargo.toml, src/lib.rs
In order to avoid triggering a link error where there didn't used to be one. #74 causes rust-lld errors like this in compilers older than nightly-2024-12-19:
```console
error: linking with `wasm-component-ld` failed: exit status: 1
|
= note: "wasm-component-ld" "-flavor" "wasm" "--export" "__main_void" "--export" "cabi_realloc" "-z" "stack-size=1048576" "--stack-first" "--allow-undefined" "--no-demangle" {...} "-l" "c" "-L" ".rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/wasm32-wasip2/lib/self-contained" "-o" "target/wasm32-wasip2/debug/deps/repro-2c59c9d65bdd9014.wasm" "--gc-sections" "-O0"
= note: rust-lld: error: target/wasm32-wasip2/debug/deps/repro-2c59c9d65bdd9014.am9l6ff8xuqu3stbvow8o8tiz.rcgu.o: invalid data symbol offset: `_ZN5repro1_6__CTOR17h2780dd13c1356084E` …
```
=> Make Wasm link section conditional on compiler version

src/lib.rs
Manually implements Clone for Iter<T> so that it does not require that T be Clone anymore.
=> Relax bounds on Clone implementation of Iter<T>
